---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app: n8n
    component: secrets
stringData:
  DB_POSTGRESDB_PASSWORD: "<Youy Password>"
  N8N_BASIC_AUTH_PASSWORD: "<Youy Password>"
  N8N_ENCRYPTION_KEY: "n8n"
